project:
  type: book
  output-dir: docs

book:
  title: "Player Load & Explosive Movement Analysis - UVA Men's Basketball"
  author: "Tristen Davin, Margaux Reynolds, Benjamin Berinsky, Ben Garozzo"
  date: last-modified
  favicon: "images/uva_logo.jpg"
  description: "How Practice Intensity May Be Affecting UVA Basketball’s Performance"
  keyword: "Dataviz, Basketball, UVA, Catapult, Data Science"
  url: "https://benberinsky.github.io/ds2023_finalproject"
  sidebar:
    search: true
    logo: "images/mens_basketball.png"
  repo-url: "https://github.com/benberinsky/ds2023_final_project"
  repo-branch: main
  image: "images/datasciencelogo.png"

  chapters:
    - index.qmd
    - datacleaning.qmd
    - eda.qmd
    - dataviz.qmd
    - datadictionary.qmd

format:
  html:
    theme: journal 
    code-fold: false
    toc: true
    df-print: paged


