project:
  type: book
  output-dir: docs

book:
  title: "INSERT REPORT TITLE"
  author: "INSERT NAMES"
  favicon: "INSERT ICON FOR REPORT"
  description: SINGLE LINE BELOW TITLE
  keyword: "Keywords for when people are searching for report"
  url: "https://benberinsky.github.io/ds2023_finalproject"
  sidebar:
    logo: sidebar picture
    search: true
  repo-url: "https://github.com/benberinsky/ds2023_finalproject"
  repo-branch: main
  image: insert image

  chapters:
    - index.qmd
    - datacleaning.qmd
    - eda.qmd
    - dataviz.qmd
    - datadictionary.qmd

format:
  html:
    theme:
      - light
    code-fold: false
    backgroundcolor: "#FFFFFF"
