project:
  type: book
  output-dir: docs

book:
  title: "INSERT REPORT TITLE"
  author: "Tristen Davin, Margaux Reynolds, Benjamin Berinsky, Ben Garozzo"
  favicon: "INSERT ICON FOR REPORT"
  description: SINGLE LINE BELOW TITLE
  keyword: "Insert keywords"
  url: "https://benberinsky.github.io/ds2023_finalproject"
  #Need to add sidebar picture as logo var later
  sidebar:
    search: true
  repo-url: "https://github.com/benberinsky/ds2023_finalproject"
  repo-branch: main
  image: insert image

  chapters:
    - index.qmd
    - datacleaning.qmd
    - eda.qmd
    - dataviz.qmd
    - datadictionary.qmd

format:
  html:
    theme:
      - light
    code-fold: false
    backgroundcolor: "#FFFFFF"
