project:
  type: book
  output-dir: docs

book:
  title: "Analyzing Player Load and Explosive Movements in UVA Mens Basketball"
  author: "Tristen Davin, Margaux Reynolds, Benjamin Berinsky, Ben Garozzo"
  favicon: "images/mens_basketball.png"
  description: An Analysis of Positional Workloads from the 2022/23 and 2023/24 Seasons
  keyword: "Dataviz, Basketball, UVA, Catapult, Data Science"
  url: "https://benberinsky.github.io/ds2023_finalproject"
  sidebar:
    search: true
    logo: "images/uva_logo.jpg"
  repo-url: "https://github.com/benberinsky/ds2023_finalproject"
  repo-branch: main
  image: insert image

  chapters:
    - index.qmd
    - datacleaning.qmd
    - eda.qmd
    - dataviz.qmd
    - datadictionary.qmd

format:
  html:
    theme:
      - flatly
    code-fold: false